name: light_compressor_example
description: Demonstrates how to use the light_compressor plugin.
version: 0.0.1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  file_picker: ^3.0.3
  flutter:
    sdk: flutter
  light_compressor:
    path: ../
  path_provider: ^2.0.2
  video_player: ^2.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
